version: '2.2'

services:
  node_bootstrap:
    build: .
    image: chrispetsos/centos6-mariadb-10.1-galera:latest
    environment:
      CLUSTER_NAME: test_cluster
      CLUSTER: BOOTSTRAP
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  node_additional:
    build: .
    image: chrispetsos/centos6-mariadb-10.1-galera:latest
    scale: 5
    depends_on:
      - node_bootstrap
    environment:
      CLUSTER_NAME: test_cluster
      CLUSTER: node_bootstrap
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  garbd:
    build:
      context: .
      dockerfile: Dockerfile.garbd
    image: chrispetsos/centos6-mariadb-10.1-garbd:latest
    command: garbd --group=test_cluster --address="gcomm://node_bootstrap"
